version: '3.9'
services:
  app:
    image: mantassidabras/alcotracker:latest
    container_name: app
    depends_on:
      - 'redis'
      - 'postgres'
    ports:
      - '4000:4000'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1g
  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1g
  postgres:
    image: 'postgres:13'
    container_name: postgres
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1g
    environment:
      - POSTGRES_DB=alcotracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nQPcdB2iSHogfS
    volumes:
      - db-data:/var/lib/postgresql/data/
  watchtower:
    container_name: watchtower
    restart: 'unless-stopped'
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug true --cleanup true app

volumes:
  db-data:
    driver: local
