name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-push-image-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build and push server
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: server
      #     file: server/Dockerfile
      #     platforms: linux/arm/v7
      #     push: true
      #     tags: mantassidabras/alcotracker:latest

      - name: Build and push client
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      - run: cd client
      - run: yarn build 
      - run: docker buildx build --platform linux/arm/v7 -t mantassidabras/alcotracker-web:latest .
      - run: docker image push alcotracker-web:latest
